FROM python:3.11-slim
WORKDIR /app
COPY backend/ ./backend
COPY frontend/ ./frontend
COPY requirements.txt ./

RUN pip install -r requirements.txt
WORKDIR /app/frontend
RUN npm install
RUN npm run build
WORKDIR /app
EXPOSE 80
CMD ["python", "backend/app.py"]
