FROM python:3.11.3-slim-buster
WORKDIR /app
COPY backend/ ./backend
COPY frontend/ ./frontend
COPY models/ ./models
COPY requirements.txt ./
COPY models.py ./

RUN pip install --no-cache-dir  -r requirements.txt
WORKDIR /app/backend
ENV port=8080
EXPOSE 8080
CMD ["python", "app.py"]
